
import '../styles/home.scss';
import '../styles/global.scss';
import '../styles/main-layout.scss';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className={'main-layout'}>
        {children}
        </main>
      </body>
    </html>
  );
}
