
import '../styles/home.scss';
import '../styles/global.scss';
import '../styles/main-layout.scss';
import '../styles/header.scss';
import '../styles/footer.scss';
import Footer from '@/components/footer/Footer';
import Header from '@/components/Header/Header';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className={'main-layout'}>
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
